### ISSUE TITLE
Filter Out NSFW

### ISSUE THREAD

**Issue by davo93** [timrodz/es-gamedev-bot#13]
Hello Team,

Usually NSFW accounts will use unrelated hashtags for exposure.

Currently if a NSFW account creates a post using one of the designed hashtags it will automatically retweeted even thought it's unrelated

I see that tweepy has a possible_sensitive flag that should help with this

**Comment by timrodz** [comment]
Closed by [!14](https://github.com/timrodz/es-gamedev-bot/pull/14)
